language: python
sudo: false

env:
  - LUA="luajit 2.0"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install luacheck
  - luarocks install busted

script:
  - luacheck .
  - busted tests/spc
  - tests/templates/validate_templates.sh

branches:
  only:
  - master
  - develop

notifications:
  email:
    on_success: change
    on_failure: always
